#! /bin/bash

python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_duff_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_duff_2
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_nestle_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_nestle_2
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_vanish_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_move_from_board_to_board_vanish_2

python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_move_from_board_to_board_nivea_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_move_from_board_to_board_nivea_2
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_move_from_board_to_board_fanta_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_move_from_board_to_board_fanta_2


python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_pick_to_basket_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_pick_to_basket_2
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_pick_to_basket_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_pick_to_basket_2

python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_pick_from_floor_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_scenes_pick_from_floor_2

python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_pick_from_floor_1
python scripts/generate_scene_continuous.py ds_continuous=test_unseen_items_pick_from_floor_2